import { useState } from "react";
import { Activity, ArrowUpRight, ClipboardCheck, Pause, Play, RefreshCw, X } from "lucide-react";
import { accountMetrics, auditEvents, executionQueue, healthChecks, overviewAnalytics, riskMetrics, strategies, type OverviewAnalyticsView } from "../fixtures/overview";
import type { Navigate } from "../types";
import { StatusBadge } from "../components/StatusBadge";

export function OverviewPage({ onNavigate }: { onNavigate: Navigate }) {
  const [confirmationOpen, setConfirmationOpen] = useState(false);
  const [confirmation, setConfirmation] = useState("");
  const [paused, setPaused] = useState(false);
  const [runPreviewOpen, setRunPreviewOpen] = useState(false);
  const [reconciliationOpen, setReconciliationOpen] = useState(false);
  const [chart, setChart] = useState<OverviewAnalyticsView>("净值");
  const chartView = overviewAnalytics[chart];

  function pauseAll() {
    if (confirmation !== "确认暂停") return;
    setPaused(true); setConfirmationOpen(false);
  }

  return <div className="overview-page">
    <div className="page-heading"><div><p className="eyebrow">COMMAND CENTER · 09:42:18 CST</p><h1>总览</h1><p>模拟执行、账户风险和系统健康的统一入口</p></div><div className="heading-actions"><button className="button button--default" onClick={() => setReconciliationOpen(true)}><RefreshCw size={15} />查看差异</button><button className="button button--danger" onClick={() => setConfirmationOpen(true)}><Pause size={15} />暂停全部策略</button><button className="button button--primary" onClick={() => setRunPreviewOpen(true)}><Play size={15} />运行本次模拟</button></div></div>
    {paused && <div className="notice notice--warning"><Pause size={16} /><span><strong>策略已暂停</strong> · 已暂停 3 个策略，运行 ID <code>run_pause_a47d0f</code>。平仓、撤单和风险处理仍可执行。</span></div>}
    <section className="panel health-panel" aria-label="系统健康"><div className="section-heading"><div><span className="section-kicker">SYSTEM HEALTH</span><h2>系统健康</h2></div><button className="text-button">打开诊断 <ArrowUpRight size={14} /></button></div><div className="health-grid">{healthChecks.map(item => <button className="health-check" key={item.label}><StatusBadge tone={item.tone}>{item.label}</StatusBadge><span>{item.detail}</span></button>)}</div></section>
    <section className="metric-strip metric-strip--dense" aria-label="账户摘要">{accountMetrics.map(metric => <Metric key={metric.label} {...metric} />)}</section>
    <section className="panel risk-panel"><div className="section-heading"><div><span className="section-kicker">RISK LIMITS</span><h2>风险摘要</h2></div><button className="text-button" onClick={() => onNavigate("risk")}>查看风险明细 <ArrowUpRight size={14} /></button></div><div className="risk-grid">{riskMetrics.map(item => <div className="risk-metric" key={item.label}><span>{item.label}</span><strong className={`tone-${item.tone}`}>{item.value}</strong><i><b style={{ width: item.value.startsWith("18") ? "93%" : item.value.startsWith("28") ? "81%" : item.value.startsWith("4") ? "55%" : "28%" }} /></i></div>)}</div></section>
    <section className="two-column"><div className="panel"><div className="section-heading"><div><span className="section-kicker">STRATEGY OPERATIONS</span><h2>策略运行</h2></div><button className="text-button" onClick={() => onNavigate("lab")}>策略实验室 <ArrowUpRight size={14} /></button></div><div className="table-wrap"><table><thead><tr><th>策略名称</th><th>状态</th><th>周期</th><th className="numeric">信号</th><th className="numeric">目标换手</th><th className="numeric">今日 P&amp;L</th><th>最近运行</th><th>操作</th></tr></thead><tbody>{strategies.map(item => <tr key={item.name}><td><strong>{item.name}</strong><small>{item.version} · {item.data}</small></td><td><StatusBadge tone={item.status === "可模拟" ? "positive" : item.status === "已暂停" ? "warning" : "neutral"}>{item.status}</StatusBadge></td><td>{item.cycle}</td><td className="numeric">{item.signals}</td><td className="numeric">{item.turnover}</td><td className="numeric positive">{item.pnl}</td><td><code>{item.run}</code></td><td><button className="text-button" onClick={() => onNavigate("runs", { runId: item.run })}>查看运行</button></td></tr>)}</tbody></table></div></div><div className="panel execution-panel"><div className="section-heading"><div><span className="section-kicker">EXECUTION QUEUE</span><h2>执行队列</h2></div><ClipboardCheck size={18} /></div><div className="queue-list">{executionQueue.map(item => <button key={item.status} className="queue-item" aria-label={`${item.status} ${item.count} 笔委托`} onClick={() => onNavigate("simulation", { executionStatus: item.status })}><StatusBadge tone={item.tone}>{item.status}</StatusBadge><strong>{item.count}</strong><span>笔委托</span><ArrowUpRight size={15} /></button>)}</div><div className="queue-footer"><span>批次 <code>batch_20260814_0942</code></span><span>待风控 3 笔</span></div></div></section>
    <section className="two-column bottom-grid"><div className="panel chart-panel"><div className="section-heading"><div><span className="section-kicker">EQUITY &amp; EXPOSURE</span><h2>净值与暴露</h2></div><div className="tab-list">{(Object.keys(overviewAnalytics) as OverviewAnalyticsView[]).map(tab => <button key={tab} onClick={() => setChart(tab)} className={chart === tab ? "active" : ""}>{tab}</button>)}</div></div><div className="chart-summary"><strong>{chartView.headline}</strong><span className="positive">近 30 个交易日 <b>{chartView.change}</b></span><span>{chartView.detail} · 当前视图：{chart}</span></div><div className="chart" aria-label={`${chart}趋势图`}><svg viewBox="0 0 640 185" preserveAspectRatio="none"><path d={chartView.path} fill="none" stroke="currentColor" strokeWidth="3"/><path d="M0 160 H640 M0 100 H640 M0 40 H640" stroke="currentColor" className="chart-grid" /></svg><div className="chart-axis"><span>07-04</span><span>07-18</span><span>08-01</span><span>08-14</span></div></div></div><div className="panel audit-panel"><div className="section-heading"><div><span className="section-kicker">AUDIT TRAIL</span><h2>审计时间线</h2></div><button className="text-button" onClick={() => onNavigate("runs")}>运行记录 <ArrowUpRight size={14} /></button></div><ol className="timeline">{auditEvents.map(event => <li key={event.time}><span className="timeline-dot"><Activity size={12} /></span><div><header><time>{event.time}</time><StatusBadge tone="neutral">{event.type}</StatusBadge></header><p>{event.summary}</p><code>{event.runId}</code></div></li>)}</ol></div></section>
    {confirmationOpen && <div className="modal-backdrop" role="presentation"><section className="confirmation" role="dialog" aria-modal="true" aria-labelledby="pause-title"><button className="icon-button close" aria-label="关闭确认" onClick={() => setConfirmationOpen(false)}><X size={18} /></button><span className="section-kicker">DANGEROUS OPERATION</span><h2 id="pause-title">暂停全部策略</h2><dl><div><dt>影响范围</dt><dd>3 个策略，5 笔待处理开仓委托</dd></div><div><dt>预计影响</dt><dd>停止新信号和新开仓；平仓、撤单和风险处理继续可用</dd></div><div><dt>生效时间</dt><dd>确认后立即生效，写入新的审计运行 ID</dd></div></dl><label>确认文本<input aria-label="确认文本" value={confirmation} onChange={event => setConfirmation(event.target.value)} placeholder="输入 确认暂停" autoFocus /></label><div className="confirmation-actions"><button className="button button--default" onClick={() => setConfirmationOpen(false)}>取消</button><button className="button button--danger" disabled={confirmation !== "确认暂停"} onClick={pauseAll}>确认暂停全部策略</button></div></section></div>}
    {reconciliationOpen && <div className="modal-backdrop" role="presentation"><section className="confirmation" role="dialog" aria-modal="true" aria-labelledby="reconciliation-title"><button className="icon-button close" aria-label="关闭对账差异" onClick={() => setReconciliationOpen(false)}><X size={18} /></button><span className="section-kicker">READ-ONLY RECONCILIATION</span><h2 id="reconciliation-title">对账差异</h2><p>只读核对</p><dl><div><dt>模拟账本快照</dt><dd><code>ledger_sim_20260814_094216</code> · 09:42:16 CST</dd></div><div><dt>风险估值快照</dt><dd><code>risk_nav_20260814_094216</code> · ¥0.00 差异</dd></div><div><dt>核对范围</dt><dd>现金、持仓市值、融资负债、融券负债与当日损益</dd></div></dl><div className="confirmation-actions"><button className="button button--default" onClick={() => setReconciliationOpen(false)}>关闭</button></div></section></div>}
    {runPreviewOpen && <div className="modal-backdrop" role="presentation"><section className="confirmation" role="dialog" aria-modal="true" aria-labelledby="run-preview-title"><button className="icon-button close" aria-label="关闭运行预览" onClick={() => setRunPreviewOpen(false)}><X size={18} /></button><span className="section-kicker">PAPER RUN PREVIEW</span><h2 id="run-preview-title">运行本次模拟预览</h2><dl><div><dt>数据时间</dt><dd>分钟行情 09:42:06 CST，延迟 12 秒</dd></div><div><dt>待执行策略</dt><dd>沪深300动量轮动 · v0.3.2</dd></div><div><dt>预计委托数</dt><dd>3 笔，全部为模拟委托</dd></div><div><dt>风险检查结果</dt><dd>单票、杠杆、当日亏损和行情新鲜度均通过</dd></div></dl><div className="confirmation-actions"><button className="button button--default" onClick={() => setRunPreviewOpen(false)}>关闭</button><button className="button button--primary" onClick={() => onNavigate("simulation", { executionStatus: "待风控" })}>查看待风控委托</button></div></section></div>}
  </div>;
}

function Metric({ label, value, detail, positive = false }: { label: string; value: string; detail: string; positive?: boolean }) { return <div className="metric"><span>{label}</span><strong className={positive ? "positive" : ""}>{value}</strong><small>{detail}</small></div>; }
