import { useState } from "react";
import { StatusBadge } from "../components/StatusBadge";
import type { Navigate, RiskAlertFilter, RiskEventState } from "../types";

const events = [
  { state: "预警", code: "RISK_CONCENTRATION", summary: "600519.SH 单票集中度接近上限", run: "run_sim_8f2c1a" },
  { state: "阻断", code: "RISK_OPENING_BLOCKED", summary: "新增买单等待风险处理", run: "run_sim_8f2c1a" },
  { state: "已解决", code: "RISK_RECONCILED", summary: "本地账本已完成只读核对", run: "run_sim_6a97b4" }
] as const;

const limits = [["单票集中度", "18.60% / 20.00%"], ["行业集中度", "28.40% / 35.00%"], ["总杠杆限额", "1.42x / 2.00x"], ["当日亏损", "0.84% / 3.00%"], ["回撤暂停", "4.36% / 8.00%"]];

export function RiskPage({ initialAlertFilter, onNavigate }: { initialAlertFilter?: RiskAlertFilter; onNavigate?: Navigate }) {
  const [filter, setFilter] = useState<RiskEventState | "全部">(initialAlertFilter ?? "全部");
  const [limitPreview, setLimitPreview] = useState(false);
  const [liquidating, setLiquidating] = useState(false);
  const [confirmation, setConfirmation] = useState("");
  const [feedback, setFeedback] = useState("");
  const shown = filter === "全部" ? events : events.filter(event => event.state === filter);
  return <>
    <div className="page-heading"><div><p className="eyebrow">ACCOUNT &amp; RISK · LOCAL PROTOTYPE SNAPSHOT</p><h1>账户与风险</h1><p>估值 2026-08-14 09:42:16 CST · 模拟账户，不连接真实柜台。</p></div><div className="heading-actions"><button className="button" onClick={() => setLimitPreview(true)}>编辑风险限额</button><button className="button button--danger" onClick={() => setLiquidating(true)}>模拟强平</button></div></div>
    {feedback && <div className="notice" role="status"><span>{feedback}</span></div>}
    <section className="metric-strip metric-strip--dense" aria-label="风险账户摘要">{["净资产|¥1,248,460.32|估值 09:42:16", "现金|¥434,980.76|可用资金", "总持仓|¥813,479.56|6 个标的", "融资负债|¥0.00|未启用", "融券负债|¥0.00|未启用", "利息|¥0.00|信用参数未启用", "维持担保比例|312.46%|模拟账户口径", "总杠杆|1.42x / 2.00x|当前 / 上限"].map(item => { const [label, value, detail] = item.split("|"); return <div className="metric" key={label}><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>; })}</section>
    <section className="panel"><div className="section-heading"><div><span className="section-kicker">POSITIONS &amp; T+1</span><h2>持仓明细</h2></div><span className="muted">总持仓 / 可用持仓 / T+1 冻结</span></div><div className="table-wrap"><table><thead><tr><th>标的</th><th className="numeric">总持仓</th><th className="numeric">可用持仓</th><th className="numeric">T+1 冻结</th><th className="numeric">成本价</th><th className="numeric">现价</th><th className="numeric">浮盈亏</th><th>策略 / 行业</th><th>边际风险贡献</th></tr></thead><tbody><tr><td><strong>600519.SH</strong></td><td className="numeric">200</td><td className="numeric">100</td><td className="numeric">100</td><td className="numeric">¥1,672.40</td><td className="numeric">¥1,703.80</td><td className="numeric positive">+¥6,280.00</td><td>动量轮动 / 消费</td><td className="numeric">27.40%</td></tr><tr><td><strong>其他持仓</strong><small>无法逐标的拆分的本地快照</small></td><td className="numeric">--</td><td className="numeric">--</td><td className="numeric">--</td><td className="numeric">--</td><td className="numeric">¥472,719.56</td><td className="numeric">--</td><td>多策略 / 多行业</td><td className="numeric">72.60%</td></tr></tbody></table></div><div className="queue-footer"><span>市值闭合：¥340,760.00 + ¥472,719.56 = ¥813,479.56</span><span>只读说明</span></div></section>
    <section className="two-column"><section className="panel"><div className="section-heading"><div><span className="section-kicker">LIMIT UTILIZATION</span><h2>风险限额</h2></div></div><div className="risk-grid">{limits.map(([label, value]) => <div className="risk-metric" key={label}><span>{label}</span><strong>{value}</strong><i><b style={{ width: "72%" }} /></i></div>)}</div></section><section className="panel"><div className="section-heading"><div><span className="section-kicker">RISK EVENTS</span><h2>风险事件</h2></div><label className="sr-only" htmlFor="risk-filter">风险事件状态筛选</label><select id="risk-filter" aria-label="风险事件状态筛选" value={filter} onChange={event => setFilter(event.target.value as RiskEventState | "全部")}><option>全部</option><option>预警</option><option>阻断</option><option>模拟强平</option><option>已解决</option></select></div><div className="queue-list">{shown.map(event => <div className="queue-item" key={event.code}><StatusBadge tone={event.state === "阻断" ? "negative" : event.state === "预警" ? "warning" : "positive"}>状态：{event.state}</StatusBadge><span>{event.summary}</span><code>{event.run}</code><span>{event.code}</span>{onNavigate && <button className="text-button" onClick={() => onNavigate("runs", { runId: event.run })}>查看运行记录</button>}</div>)}</div></section></section>
    {limitPreview && <div className="modal-backdrop"><section className="confirmation" role="dialog" aria-label="风险限额影响预览"><h2>风险限额影响预览</h2><dl><div><dt>新配置版本</dt><dd>CONFIG-RISK-20260814.4</dd></div><div><dt>影响范围</dt><dd>后续创建的模拟运行与开仓检查</dd></div><div><dt>预计行为</dt><dd>单票集中度上限从 20.00% 调整为 18.00%</dd></div><div><dt>生效时间</dt><dd>2026-08-14 09:45:00 CST</dd></div><div><dt>旧值</dt><dd>20.00%</dd></div><div><dt>新值</dt><dd>18.00%</dd></div></dl><div className="confirmation-actions"><button className="button" onClick={() => setLimitPreview(false)}>取消</button><button className="button button--primary" onClick={() => { setLimitPreview(false); setFeedback("已保存风险限额版本 CONFIG-RISK-20260814.4"); }}>保存风险限额版本</button></div></section></div>}
    {liquidating && <div className="modal-backdrop"><section className="confirmation" role="dialog" aria-label="模拟强平确认"><h2>模拟强平确认</h2><p>影响范围：按边际风险贡献处理模拟持仓；预计释放 ¥232,500.00；不发送真实委托。</p><label>确认文本<input aria-label="确认文本" value={confirmation} onChange={event => setConfirmation(event.target.value)} placeholder="确认模拟强平" /></label><div className="confirmation-actions"><button className="button" onClick={() => setLiquidating(false)}>取消</button><button className="button button--danger" disabled={confirmation !== "确认模拟强平"} onClick={() => { setLiquidating(false); setFeedback("已创建模拟运行 run_liq_94af · 不发送真实委托"); }}>确认模拟强平</button></div></section></div>}
  </>;
}
