import { useEffect, useState } from "react";
import { RefreshCw } from "lucide-react";
import { getRuns, type RunsResponse } from "../api";
import type { RunStatusFilter } from "../types";

export function RunsPage({ initialRunId, initialStatus }: { initialRunId?: string; initialStatus?: RunStatusFilter }) { const [data, setData] = useState<RunsResponse | null>(null); const [error, setError] = useState(""); const [filter, setFilter] = useState(initialStatus ?? "全部"); const load = () => { getRuns().then(value => { if (!value?.runs) throw new Error("API 返回的运行记录不完整"); setData(value); }).catch(e => setError(e instanceof Error ? e.message : "运行记录不可用")); }; useEffect(() => { load(); }, []); const runs = data?.runs.filter(r => filter === "全部" || (filter === "已完成" && r.status === "completed") || (filter === "失败" && r.status === "error") || (filter === "运行中" && r.status === "running")) ?? [];
  if (!data && !error) return <div className="panel panel-body"><h1>运行记录</h1><p>正在加载后端运行记录...</p></div>; if (error) return <div className="panel panel-body"><h1>运行记录</h1><p role="alert">运行记录不可用：{error}</p><button className="button" onClick={load}><RefreshCw size={15}/>重试</button></div>;
  return <><div className="page-heading"><div><p className="eyebrow">RUN RECORDS · API READ MODEL</p><h1>运行记录</h1><p>后端当前进程创建的研究与回测运行</p></div><button className="button" onClick={load}><RefreshCw size={15}/>刷新</button></div>{initialRunId && <div className="notice">已保留运行上下文：<code>{initialRunId}</code></div>}<section className="health-grid"><div className="health-check"><span>总运行</span><strong>{data!.total}</strong></div><div className="health-check"><span>已完成</span><strong>{data!.runs.filter(r => r.status === "completed").length}</strong></div><div className="health-check"><span>运行中</span><strong>{data!.runs.filter(r => r.status === "running").length}</strong></div></section><section className="panel"><div className="section-heading"><h2>任务列表</h2><label>状态<select aria-label="运行状态筛选" value={filter} onChange={e => setFilter(e.target.value as RunStatusFilter)}><option>全部</option><option>运行中</option><option>已完成</option><option>失败</option></select></label></div><div className="table-wrap"><table><thead><tr><th>运行 ID</th><th>策略</th><th>数据</th><th>状态</th><th>创建时间</th></tr></thead><tbody>{runs.map(run => <tr key={run.runId}><td><code>{run.runId}</code></td><td>{run.strategyVersion}</td><td>{run.dataVersion}</td><td>{run.status}</td><td>{new Date(run.createdAt).toLocaleString("zh-CN")}</td></tr>)}</tbody></table></div></section></>;
}
